version: 2

conda:
  environment: .rtd-env-py3.yml

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - meshmode @ git+https://github.com/inducer/meshmode.git#egg=meshmode
