name: rtd-env-py3
channels:
- conda-forge
- nodefaults
dependencies:
- python=3.8
- mpi4py
- islpy
- pip
- pyopencl
- pip:
  - "git+https://github.com/inducer/pymbolic.git#egg=pymbolic"
  - "git+https://github.com/inducer/loopy.git#egg=loopy"
  - "git+https://github.com/inducer/dagrt.git#egg=dagrt"
  - "git+https://github.com/inducer/leap.git#egg=leap"
  - "git+https://github.com/inducer/modepy.git#egg=modepy"
  - "git+https://github.com/inducer/arraycontext.git#egg=arraycontext"
  - "git+https://github.com/inducer/meshmode.git#egg=meshmode"
  - "git+https://github.com/inducer/grudge.git#egg=grudge"
  - "sphinx-math-dollar"
  - "sphinx-copybutton"
  - "furo"

