# Conda env file for the readthedocs build
name: rtd-env-py3
channels:
- conda-forge
- nodefaults
dependencies:
# readthedocs does not yet support Python 3.11
# See e.g. https://readthedocs.org/api/v2/build/18650881.txt
- python=3.10
- mpi4py
- islpy
- pip
- pyopencl
- pip:
  - "git+https://github.com/inducer/pymbolic.git#egg=pymbolic"
  - "git+https://github.com/inducer/loopy.git#egg=loopy"
  - "git+https://github.com/inducer/dagrt.git#egg=dagrt"
  - "git+https://github.com/inducer/leap.git#egg=leap"
  - "git+https://github.com/inducer/modepy.git#egg=modepy"
  - "git+https://github.com/inducer/arraycontext.git#egg=arraycontext"
  - "git+https://github.com/majosm/meshmode.git@production#egg=meshmode"
  - "git+https://github.com/majosm/grudge.git@coupled-volumes#egg=grudge"
  - "sphinx-math-dollar"
  - "sphinx-copybutton"
  - "furo"

