name: test-conda-env-py3
channels:
- conda-forge
- nodefaults
dependencies:
- git

# https://github.com/illinois-ceesd/mirgecom/issues/212
- jemalloc

- conda-forge::numpy
- pocl
- clinfo
- islpy
- oct2py
- pyopencl
- pymetis
- python=3.8
- gmsh
- pip
- pytest
- libhwloc=1
