name: test-conda-env-py3
channels:
- conda-forge
- nodefaults
dependencies:
- git
- conda-forge::numpy
- pocl
- clinfo
- islpy
- oct2py
- pyopencl
- pymetis
- python=3.8
- gmsh
- pip
- pytest
- libhwloc=1
- cantera
