# Conda packages needed by mirgecom.
# The packages listed here are common to all OS/architectures,
# Some OS-specific packages are installed directly by emirge.
#
name: ceesd
channels:
- conda-forge
- nodefaults
dependencies:
- git
- gh
- mypy
- conda-forge::numpy
# See https://github.com/illinois-ceesd/mirgecom/pull/1055:
- pocl=5.0=*_6
- nvtop
- clinfo
- pudb
- islpy
- oct2py
- pyopencl
- pymetis
- python=3.13
- pip
- pytest
- pylint
- pydocstyle
# See https://github.com/conda-forge/cantera-feedstock/issues/46 why we need 3.0.0:
- cantera=3.0.1
- h5py * nompi_*  # Make sure cantera does not pull in MPI through h5py
- gmsh
- vtk
