# Conda packages needed by mirgecom.
# The packages listed here are common to all OS/architectures,
# Linux systems also need pocl-cuda (which is installed directly by emirge).
#
name: ceesd
channels:
- conda-forge
- nodefaults
dependencies:
- git
- conda-forge::numpy
- pocl
- clinfo
- islpy
- oct2py
- pyopencl
- pymetis
- python=3.8
- pip
- pytest
- cantera
