# Conda packages needed by mirgecom.
# The packages listed here are common to all OS/architectures,
# Linux systems also need pocl-cuda (which is installed directly by emirge).
#
name: ceesd
channels:
- conda-forge
- nodefaults
dependencies:
- git
- gh
- conda-forge::numpy
- pocl
- clinfo
- pudb
- islpy
- oct2py
- pyopencl
- pymetis
- python=3.11
- pip
- pytest
- pylint
- pydocstyle
- gmsh
