# Conda packages needed by mirgecom.
# The packages listed here are common to all OS/architectures,
# Linux systems also need pocl-cuda (which is installed directly by emirge).
#
name: ceesd
channels:
- conda-forge
- nodefaults
dependencies:
- git
- gh
- mypy
- conda-forge::numpy
- pocl
- clinfo
- islpy
- oct2py
- pyopencl
- pymetis
- python=3.9

# https://github.com/pypa/setuptools/issues/2969
- setuptools!=60.1.0
- pip

- pytest
- cantera
- h5py * nompi_*  # Make sure cantera does not pull in MPI through h5py
- vtk
