[tool.ruff]
target-version = "py38"
preview = true

[tool.ruff.lint]
extend-select = [
    "B",   # flake8-bugbear
    "C",   # flake8-comprehensions
    "E",   # pycodestyle
    "F",   # pyflakes
    "G",   # flake8-logging-format
    "I",   # flake8-isort
    "N",   # pep8-naming
    "NPY", # numpy
    "Q",   # flake8-quotes
    "UP",  # pyupgrade
    "RUF", # ruff
    "W",   # pycodestyle
]
extend-ignore = [
    "B023", # Function definition does not bind loop variable"
    "C90",  # McCabe complexity
    "E221", # multiple spaces before operator
    "E226", # missing whitespace around arithmetic operator
    "E402", # module-level import not at top of file
    "UP006", # updated annotations due to __future__ import
    "UP007", # updated annotations due to __future__ import
    "B028", # No explicit `stacklevel` keyword argument
    "G003", # Logging statement uses `+`
    "G004", # Logging statement uses f-string
]

[tool.ruff.lint.flake8-quotes]
docstring-quotes = "double"
inline-quotes = "double"
multiline-quotes = "double"

[tool.ruff.lint.isort]
combine-as-imports = true
known-local-folder = [
    "mirgecom",
]
known-first-party = [
  "pytools",
  "pyopencl",
  "pytato",
  "loopy",
]
lines-after-imports = 2

[tool.mypy]
python_version = "3.8"
warn_unused_ignores = true
# TODO: enable this
# check_untyped_defs = true

[[tool.mypy.overrides]]

module = [
  "islpy",
  "loopy.*",
  "meshmode.*",
  "pymbolic",
  "pymbolic.*",
  "pyopencl.*",
  "jax.*",
]

ignore_missing_imports = true
