#!/bin/bash
#
# Used to wrap the spawning of parallel mirgecom drivers on Tioga.
export CUDA_CACHE_DISABLE=0

MIRGE_CACHE_ROOT=${MIRGE_CACHE_ROOT:-"$(pwd)"}
POCL_CACHE_ROOT=${POCL_CACHE_ROOT:-"${MIRGE_CACHE_ROOT}/pocl-cache"}
XDG_CACHE_ROOT=${XDG_CACHE_ROOT:-"${MIRGE_CACHE_ROOT}/xdg-cache"}
CUDA_CACHE_ROOT=${CUDA_CACHE_ROOT:-"${MIRGE_CACHE_ROOT}/cuda-cache"}

POCL_CACHE_DIR=${POCL_CACHE_DIR:-"${POCL_CACHE_ROOT}/rank$FLUX_TASK_RANK"}
XDG_CACHE_HOME=${XDG_CACHE_HOME:-"${XDG_CACHE_ROOT}/rank$FLUX_TASK_RANK"}
CUDA_CACH_PATH=${CUDA_CACHE_DIR:-"${CUDA_CACHE_ROOT}/rank$FLUX_TASK_RANK"}

export POCL_CACHE_DIR
export XDG_CACHE_HOME
export CUDA_CACHE_PATH

export ROCR_VISIBLE_DEVICES=$FLUX_TASK_LOCAL_ID

"$@"
