name: Flake8

# Trigger the workflow on push
on:
  push:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Flake8 test
          run: |
            pip install wheel flake8 pep8-naming
            python -m flake8
